name: Deploy Game Staging

on:
  push:
    branches:
      - game-staging

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: Roblox/setup-foreman@v1
      name: Install Foreman
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - run: rojo build -o time-scrappers-game-s.rbxlx

    - run: rbxcloud experience publish -f time-scrappers-game-s.rbxlx -p 17627889157 -u 6036715160 -t published -a ${{ secrets.RBXCLOUD_API_KEY }} # stage game
